const { chromium } = require('@playwright/test');
const fs = require('node:fs');
const path = require('node:path');
const assert = require('node:assert/strict');
const root = path.resolve(__dirname, '../..');
const info = JSON.parse(fs.readFileSync(path.join(root, 'output/fgf-local/current.json'), 'utf8'));
const output = path.join(root, 'output/playwright/admin-users');
fs.mkdirSync(output, { recursive: true });
const suffix = Date.now().toString(36).slice(-7);
const username = 'crud' + suffix;
const renamed = 'edit' + suffix;
const email = username + '@example.test';
(async () => {
  const executablePath = [process.env.PLAYWRIGHT_CHROMIUM_EXECUTABLE, 'C:/Program Files/Google/Chrome/Application/chrome.exe', chromium.executablePath()].filter(Boolean).find(p => fs.existsSync(p));
  const browser = await chromium.launch({ executablePath, headless: true });
  const context = await browser.newContext({ viewport: { width: 1440, height: 1000 } });
  const page = await context.newPage();
  const errors = [];
  page.on('pageerror', err => errors.push(err.message));
  let createdID;
  try {
    await page.goto(info.idp + '/admin');
    await page.getByLabel('帳號 / Email', { exact: true }).fill(info.username);
    await page.getByLabel('密碼', { exact: true }).fill(info.password);
    const before = (await fetch(info.mailbox + '/messages').then(r => r.json())).length;
    await page.getByRole('button', { name: '登入', exact: true }).click();
    // A fresh browser context is an unverified device: the console sends a link to the local mailbox.
    await page.locator('#signin-feedback.notice').waitFor();
    let mail = []; for (let i = 0; i < 40 && mail.length <= before; i++) { mail = await fetch(info.mailbox + '/messages').then(r => r.json()); if (mail.length <= before) await new Promise(r => setTimeout(r, 200)); }
    const link = mail.at(-1)?.match(/http:\/\/127\.0\.0\.1:15525\/x\/verify\?t=[A-Za-z0-9._~%+-]+/);
    assert(link, 'console verification email missing');
    await page.goto(link[0]);
    await page.getByRole('button', { name: '新增使用者', exact: true }).waitFor();
    const rootRow = page.locator('#user-rows tr').filter({ hasText: info.username });
    assert(await rootRow.getByRole('button', { name: '編輯', exact: true }).isDisabled());
    assert(await rootRow.getByRole('button', { name: '刪除', exact: true }).isDisabled());
    await page.getByRole('button', { name: '新增使用者', exact: true }).click();
    fs.writeFileSync(path.join(output, 'create-form.yml'), await page.locator('body').ariaSnapshot());
    await page.locator('#user-form').getByLabel('帳號', { exact: true }).fill(username);
    await page.locator('#user-form').getByLabel('顯示名稱', { exact: true }).fill('CRUD 測試');
    await page.locator('#user-form').getByLabel('Email', { exact: true }).fill(email);
    await page.locator('#user-form').getByLabel('初始密碼', { exact: true }).fill('Browser-crud-password-123');
    assert.deepEqual(await page.locator('#user-role option').evaluateAll(options => options.map(option => option.value)), ['0', '1', '4']);
    await page.screenshot({ path: path.join(output, 'create-desktop.png'), fullPage: true });
    await page.getByRole('button', { name: '建立使用者', exact: true }).click();
    await page.locator('#feedback').filter({ hasText: '已建立使用者。' }).waitFor();
    let row = page.locator('#user-rows tr').filter({ hasText: username });
    await row.waitFor();
    createdID = await row.getAttribute('data-id');
    const response = await context.request.get(info.idp + '/x/admin/users/' + createdID);
    assert.equal(response.status(), 200);
    const user = await response.json();
    assert.equal(user.username, username); assert.equal(user.role, 1);
    assert(!Object.hasOwn(user, 'password') && !Object.hasOwn(user, 'salt') && !Object.hasOwn(user, 'access_token'));
    await row.getByRole('button', { name: '編輯', exact: true }).click();
    await page.getByRole('heading', { name: '編輯使用者', exact: true }).waitFor();
    assert.equal(await page.locator('#user-password').isVisible(), false);
    await page.locator('#user-form').getByLabel('帳號', { exact: true }).fill(renamed);
    await page.locator('#user-form').getByLabel('顯示名稱', { exact: true }).fill('已修改名稱');
    await page.locator('#user-form').getByLabel('Email', { exact: true }).fill(renamed + '@example.test');
    await page.getByRole('button', { name: '儲存變更', exact: true }).click();
    await page.locator('#feedback').filter({ hasText: '已更新使用者。' }).waitFor();
    row = page.locator('#user-rows tr').filter({ hasText: renamed }); await row.waitFor();
    assert((await row.innerText()).includes('已修改名稱'));
    await page.reload();
    await page.getByRole('button', { name: '新增使用者', exact: true }).waitFor();
    await page.getByLabel('搜尋使用者').fill(renamed);
    row = page.locator('#user-rows tr').filter({ hasText: renamed }); await row.waitFor();
    await page.screenshot({ path: path.join(output, 'updated-user.png'), fullPage: true });
    await page.getByRole('button', { name: '新增使用者', exact: true }).click();
    await page.locator('#user-form').getByLabel('帳號', { exact: true }).fill('dup' + suffix);
    await page.locator('#user-form').getByLabel('Email', { exact: true }).fill(renamed + '@example.test');
    await page.locator('#user-form').getByLabel('初始密碼', { exact: true }).fill('Browser-crud-password-123');
    await page.getByRole('button', { name: '建立使用者', exact: true }).click();
    await page.locator('#feedback').filter({ hasText: '帳號或 Email 已被使用' }).waitFor();
    assert.equal(await page.locator('#user-password').inputValue(), '');
    await page.setViewportSize({ width: 390, height: 844 });
    assert(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth));
    await page.screenshot({ path: path.join(output, 'create-mobile.png'), fullPage: true });
    await page.getByRole('button', { name: '取消', exact: true }).click();
    await page.setViewportSize({ width: 1440, height: 1000 });
    page.once('dialog', dialog => dialog.accept());
    await row.getByRole('button', { name: '刪除', exact: true }).click();
    await page.locator('#feedback').filter({ hasText: '已刪除使用者。' }).waitFor();
    await row.waitFor({ state: 'detached' });
    assert.equal((await context.request.get(info.idp + '/x/admin/users/' + createdID)).status(), 404);
    assert.deepEqual(errors, []);
    console.log('PASS admin browser create / read / edit / reload / duplicate rejection / delete / root protection / mobile layout');
  } finally {
    if (createdID) await context.request.delete(info.idp + '/x/admin/users/' + createdID).catch(() => {});
    await browser.close();
  }
})().catch(err => { console.error(err); process.exitCode = 1; });
